spring.application.name=devGroveBack

spring.datasource.url=jdbc:mysql://localhost:3306/devGroveDB
spring.datasource.username=root
spring.datasource.password=123456

server.port=8081

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.web.resources.static-locations=classpath:/public/,classpath:/static/,classpath:/resources/,classpath:/META-INF/resources/

logging.level.root=info
logging.level.com.example.devgroveback=info

spring.servlet.multipart.max-file-size=100MB